// GENERATED CODE - DO NOT MODIFY MANUALLY
// **************************************************************************
// Auto generated by SoftDreams Developer
// **************************************************************************
// ignore_for_file: constant_identifier_names, non_constant_identifier_names

class Assets {
  const Assets._();
  static const String package = 'mobile_base_clean';

  static bool isFromModules = false;

  /// {@macro assets_generator.ASSETS_ICONS_IC_FAILURE_SVG.preview}
  static String get ASSETS_ICONS_IC_FAILURE_SVG =>
      '${isFromModules ? "packages/$package/" : ""}assets/icons/ic_failure.svg';

  /// {@macro assets_generator.ASSETS_ICONS_IC_NOTE_SVG.preview}
  static String get ASSETS_ICONS_IC_NOTE_SVG =>
      '${isFromModules ? "packages/$package/" : ""}assets/icons/ic_note.svg';

  /// {@macro assets_generator.ASSETS_ICONS_IC_SNACK_BAR_FAILURE_SVG.preview}
  static String get ASSETS_ICONS_IC_SNACK_BAR_FAILURE_SVG =>
      '${isFromModules ? "packages/$package/" : ""}assets/icons/ic_snack_bar_failure.svg';

  /// {@macro assets_generator.ASSETS_ICONS_IC_SNACK_BAR_SUCCESS_SVG.preview}
  static String get ASSETS_ICONS_IC_SNACK_BAR_SUCCESS_SVG =>
      '${isFromModules ? "packages/$package/" : ""}assets/icons/ic_snack_bar_success.svg';

  /// {@macro assets_generator.ASSETS_ICONS_IC_SUCCESS_SVG.preview}
  static String get ASSETS_ICONS_IC_SUCCESS_SVG =>
      '${isFromModules ? "packages/$package/" : ""}assets/icons/ic_success.svg';

  static String get ASSETS_LOCALES_VI_VN_JSON =>
      '${isFromModules ? "packages/$package/" : ""}assets/locales/vi_VN.json';
}

final List<String> assetsArray = <String>[
  /// {@macro assets_generator.ASSETS_ICONS_IC_FAILURE_SVG.preview}
  Assets.ASSETS_ICONS_IC_FAILURE_SVG,

  /// {@macro assets_generator.ASSETS_ICONS_IC_NOTE_SVG.preview}
  Assets.ASSETS_ICONS_IC_NOTE_SVG,

  /// {@macro assets_generator.ASSETS_ICONS_IC_SNACK_BAR_FAILURE_SVG.preview}
  Assets.ASSETS_ICONS_IC_SNACK_BAR_FAILURE_SVG,

  /// {@macro assets_generator.ASSETS_ICONS_IC_SNACK_BAR_SUCCESS_SVG.preview}
  Assets.ASSETS_ICONS_IC_SNACK_BAR_SUCCESS_SVG,

  /// {@macro assets_generator.ASSETS_ICONS_IC_SUCCESS_SVG.preview}
  Assets.ASSETS_ICONS_IC_SUCCESS_SVG,
  Assets.ASSETS_LOCALES_VI_VN_JSON,
];
